#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: eureka-server
#  namespace: ebikes
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: eureka-server
#  template:
#    metadata:
#      labels:
#        app: eureka-server
#    spec:
#      containers:
#        - name: eureka-server
#          image: microservices-eureka-server:latest
#          ports:
#            - containerPort: 8761
#          envFrom:
#            - configMapRef:
#                name: ebikes-config
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8761
#            initialDelaySeconds: 10
#            periodSeconds: 5
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8761
#            initialDelaySeconds: 20
#            periodSeconds: 10
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: eureka-server
#  namespace: ebikes
#spec:
#  selector:
#    app: eureka-server
#  ports:
#    - port: 8761
#      targetPort: 8761